### ISSUE TITLE
Sparkfun Bootloader Firmware

### ISSUE THREAD

**Issue by jchidley** [sparkfun/nRF52840_Breakout_MDBT50Q#2]
I recently corrupted the bootloader on my nRF52840.  I have 2 problems:
1. I need extra hardware to program the bootloader (J-Link for EDU for example or Nordic Semiconductor’s Development Kit).
2. I need a copy of Sparkfun’s  - which is “heavily based on” Adafruit’s.

Where can I find Sparkfun’s version of the firmware?

**Comment by brhoff720** [comment]
See [SparkFun Forums](https://forum.sparkfun.com/viewtopic.php?f=114&t=50217) for solution.
