### ISSUE TITLE
Adafruit nRF52 v0.11.1

### ISSUE THREAD

**Issue by jakelstr** [sparkfun/nRF52840_Breakout_MDBT50Q#3]
There seems to be an issue with this when using v0.11.1 of the Adafruit library. On v0.11.1, compiling gives an error that "Serial was not declared in this scope". Reverting to v0.10.1 cleared this error.

**Comment by masonevans** [comment]
I experienced the same issue with the same resolution

**Comment by santaimpersonator** [comment]
Adafruit switched to using TinyUSB in the core. We made changes in the `variant.cpp` and `boards.txt` files to update the board definition to use TinyUSB.

Using the new files will allow you to compile without this error and to use the example in our hookup guide.
