### ISSUE TITLE
Compile error - fatal error: usb.h: No such file or directory

### ISSUE THREAD

**Issue by masonevans** [sparkfun/nRF52840_Breakout_MDBT50Q#4]
After the latest update seems like there is still an issue in variant.cpp.   I updated to Adafruit nRF52 v0.11.1, updated my boards.txt from the latest version in this repo, and copied the sparkfun_nrf52840_mini directory into my variants folder.  

I now get the following error when I try to compile anything with the SparkFun board selected.  The other boards that come with the Adafruit nRF52 board definitions in work fine.

```
/Users/user/Library/Arduino15/packages/adafruit/hardware/nrf52/0.11.1/variants/sparkfun_nrf52840_mini/variant.cpp:26:10: fatal error: usb.h: No such file or directory
 #include "usb.h"
          ^~~~~~~
compilation terminated.
exit status 1
Error compiling for board SparkFun Pro nRF52840 Mini.
```

Commenting out the include from variant.cpp seems to fix the issue.  I do notice that Adafruit removed that include from all their variants when they removed the usb_init() call.

What's odd is that this seemed to work yesterday when I switched to v0.11.1 but today I switched back to v0.10.1 for some testing and when I went back to v0.11.1 I hit this.  Possibly something was cached somewhere?

**Comment by santaimpersonator** [comment]
I missed it in the changes I made... to update the board def. Fixed now
