### ISSUE TITLE
nRF52840 definition issue

### ISSUE THREAD

**Issue by deldipso** [sparkfun/nRF52840_Breakout_MDBT50Q#5]
Hello,

I think on this board:
SparkFun Pro nRF52840
The definition file varioant.h for the ANX pi is not correct

/*
* Analog pins
*/
//Is:
// #define PIN_A0 (2)
// #define PIN_A1 (3)
// #define PIN_A2 (31)
// #define PIN_A3 (30)
// #define PIN_A4 (29)
// #define PIN_A5 (28)
// #define PIN_A6 (5)
// #define PIN_A7 (4)
//Should be:
#define PIN_A0 (2)
#define PIN_A1 (3)
#define PIN_A2 (4)
#define PIN_A3 (5)
#define PIN_A4 (29)
#define PIN_A5 (28)
#define PIN_A6 (30)
#define PIN_A7 (31)

**Comment by bboyho** [comment]
Hi,

I'm not sure where you are seeing this but the **variants.h** file was updated in this commit => 
https://github.com/sparkfun/nRF52840_Breakout_MDBT50Q/commit/05e9122c7a8862b7d0c6ada84ba239080116efc5 . The latest file in this repo is up to date. Also, it looks like you might have listed the wrong pin for `PIN_A4` and `PIN_A5`.

**Comment by bboyho** [comment]
Closing for now. If this is still an issue, we can reopen. I believe @SFEMark resolved this issue and updated relevant documentation in December.
